sudo: false
language: node_js

node_js:
  - "node"
  - "6"
  - "4"
  - "0.12"
  - "0.10"

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "4"
    - node_js: "0.12"
    - node_js: "0.10"

notifications:
  email: false

after_success: bash <(curl -s https://codecov.io/bash)
